apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-basic-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
  - name: {{ .Release.Name }}-basic-test
    image: {{ .Values.image }}
    command: ["sh", "-c", "ls"]
  restartPolicy: Never
